import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { LinksProvider } from "@/app/context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Link Sharing App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body className={`bg-lightGrey`}>
        <LinksProvider>{children}</LinksProvider>
      </body>
    </html>
  );
}
